apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-go-2.0
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 2
  selector:
    matchLabels:
      app: app-go
  template:
    metadata:
      labels:
        app: app-go
    spec:
      containers:
        - name: mini-go-service
          image: martooo/mini-go:v1
          ports:
            - containerPort: 8080
          env:
            - name: PUERTO
              valueFrom:
                configMapKeyRef:
                  name: configmap-port
                  key: PORT
          volumeMounts:
            - mountPath: "/home/storage/"
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc-mini-go
