apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mini-go
spec:
  storageClassName: mini-go-service
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/storage"
