apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
    [smtp]
    enabled = true
    host = smtp.gmail.com:465
    user = ${USER}
    password = ${PASSWORD}
    skip_verify = true
    from_address = ${USER}
    from_name = Grafana
    
kind: ConfigMap
metadata:
  name: grafana

