#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: pv-grafana
#spec:
#  storageClassName: grafana
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/home/data"
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi  
  hostPath:
    path: /tmp/hostpath-provisioner/grafanaa/grafana-pvc
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: grafana
status:
  phase: Bound

