apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    description: Storage class para mi pod de grafana
  name: grafana
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
