apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prometheus
    prometheus.io/probe: pushgateway
  creationTimestamp: "2023-06-29T04:35:07Z"
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/version: v1.5.1
    helm.sh/chart: prometheus-pushgateway-2.0.4
  name: prometheus-prometheus-pushgateway
  namespace: prometheus
  resourceVersion: "1883866"
  uid: 2f1aaaa7-f130-4625-9d13-970f14c95ab6
spec:
  clusterIP: 10.98.27.29
  clusterIPs:
  - 10.98.27.29
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus-pushgateway
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
